import { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';
import { CommandStrip } from '../components/dashboard/CommandStrip';
import { useAuth } from '../context/AuthContext';
import { useTenant } from '../context/TenantContext';
import { useLocation } from 'wouter';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { getOwnerDocumentLabel } from '../types/documents';

export default function DiagnosticReview() {
  const { user, logout } = useAuth();
  const { tenant } = useTenant();
  const [, setLocation] = useLocation();
  const [activeDocId, setActiveDocId] = useState<string | null>(null);
  const [docContent, setDocContent] = useState<string | null>(null);
  const [loadingContent, setLoadingContent] = useState(false);

  const { data: documentsData, isLoading } = useQuery({
    queryKey: ['documents'],
    queryFn: () => api.listDocuments(),
  });

  const handleLogout = () => {
    logout();
    setLocation('/');
  };

  const documents = documentsData?.documents || [];

  // Filter and sort diagnostic docs in desired order
  const titleOrder = [
    'Company Diagnostic Map',
    'AI Leverage & Opportunity Map',
    'Strategic Roadmap Skeleton',
    'Discovery Call Preparation Questions',
  ];

  const diagnosticDocs = documents
    .filter((doc: any) => titleOrder.includes(doc.title))
    .sort((a: any, b: any) => {
      return titleOrder.indexOf(a.title) - titleOrder.indexOf(b.title);
    });

  const activeDoc = activeDocId
    ? documents.find((d: any) => d.id === activeDocId)
    : diagnosticDocs[0];

  // Auto-select first doc
  useEffect(() => {
    if (!activeDocId && diagnosticDocs.length > 0) {
      setActiveDocId(diagnosticDocs[0].id);
    }
  }, [activeDocId, diagnosticDocs]);

  // Fetch document content when active doc changes
  useEffect(() => {
    if (!activeDocId) return;

    setLoadingContent(true);
    setDocContent(null);

    const token = localStorage.getItem('token');
    fetch(`/api/documents/${activeDocId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        setDocContent(data.document.content);
      })
      .catch(err => {
        console.error('Failed to load document content:', err);
        setDocContent('Failed to load document content.');
      })
      .finally(() => setLoadingContent(false));
  }, [activeDocId]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 pb-12">
      <CommandStrip
        firmName={user?.name || 'Organization'}
        cohort="Eugene Q1 2026"
        onScheduleCall={() => window.location.href = 'mailto:tony@scend.cash?subject=Schedule Discovery Call'}
        onOpenRoadmap={() => setLocation('/roadmap')}
        onLogout={handleLogout}
        isSuperadmin={(user?.role as string) === 'superadmin'}
        onSuperadminClick={() => setLocation('/superadmin')}
        isRoadmapGenerated={false}
      />

      <div className="p-6">
        {isLoading ? (
          <div className="max-w-6xl mx-auto py-12 text-center text-slate-400">Loading diagnostics...</div>
        ) : diagnosticDocs.length === 0 ? (
          <div className="max-w-4xl mx-auto bg-slate-900/60 border border-slate-800 rounded-lg p-12 text-center">
            {tenant?.latestDiagnostic && (tenant.latestDiagnostic.status === 'generated' || tenant.latestDiagnostic.status === 'locked') ? (
              <>
                <div className="flex items-center justify-center gap-3 text-indigo-400 font-bold text-sm uppercase mb-4">
                  <span className="w-2.5 h-2.5 rounded-full bg-indigo-500 animate-pulse" />
                  {tenant.latestDiagnostic.status === 'generated' ? 'Advisor Review In Progress' : 'Finalizing for Release'}
                </div>
                <p className="text-slate-300 text-lg">
                  {tenant.latestDiagnostic.status === 'generated'
                    ? 'Your Diagnostic is generated and in advisor review.'
                    : 'Your Diagnostic has been finalized by your advisor and is being prepared for release.'}
                </p>
                <p className="text-slate-500 text-sm mt-2">It will appear here once finalized by our strategic team.</p>
                {tenant.latestDiagnostic.generatedAt && (
                  <p className="text-[10px] text-slate-600 mt-6 uppercase tracking-widest font-medium">
                    Generated on {new Date(tenant.latestDiagnostic.generatedAt).toLocaleDateString()}
                  </p>
                )}
              </>
            ) : (
              <>
                <p className="text-slate-400 text-lg">No diagnostic documents available yet.</p>
                <p className="text-slate-500 text-sm mt-2">These will appear here once generated by the strategic team.</p>
              </>
            )}
          </div>
        ) : (
          <div className="max-w-6xl mx-auto">
            {/* Tabs */}
            <div className="flex gap-1 mb-8 border-b border-slate-800 overflow-x-auto">
              {diagnosticDocs.map((doc: any) => {
                const { title: displayTitle } = getOwnerDocumentLabel(doc);
                const isActive = doc.id === activeDocId;
                return (
                  <button
                    key={doc.id}
                    onClick={() => setActiveDocId(doc.id)}
                    className={`px-6 py-4 text-sm font-medium whitespace-nowrap transition-all relative ${isActive
                      ? 'text-emerald-400'
                      : 'text-slate-400 border-transparent hover:text-slate-200'
                      }`}
                  >
                    {displayTitle}
                    {isActive && (
                      <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-400" />
                    )}
                  </button>
                );
              })}
            </div>

            {/* Active Document */}
            {activeDoc && (
              <div className="bg-slate-900/40 border border-slate-800 rounded-xl p-8 lg:p-12 shadow-xl">
                <div className="prose prose-invert prose-slate max-w-none prose-emerald">
                  {loadingContent ? (
                    <div className="flex items-center justify-center py-12">
                      <div className="text-slate-400 animate-pulse">Loading document content...</div>
                    </div>
                  ) : docContent ? (
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{docContent}</ReactMarkdown>
                  ) : (
                    <div className="text-slate-400 text-center py-12 italic">No content available for this section.</div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
